import re
import unicodedata
import logging
from pathlib import Path

from App.settings_all import get_settings_all

import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    AutoProcessor,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
    BitsAndBytesConfig
)
from peft import LoraConfig, PeftModel, get_peft_model


PROJECT_ROOT = Path(get_settings_all().PROJECT_ROOT)

LORA_ROOT = str(PROJECT_ROOT / "App" / "LLMs_Train" / "models_lora")
DEFAULT_QWEN_MODEL_ID = "qwen3_4b_instruct_2507"
DEFAULT_QWEN_REPO_ID = "Qwen/Qwen3-4B-Instruct-2507"
TRAIN_LOG_PATH = PROJECT_ROOT / "App" / "LLMs_Train" / "train_api.log"
GEMMA4_ATTENTION_LINEAR_TARGETS = (
    "self_attn.q_proj.linear",
    "self_attn.v_proj.linear",
)
GEMMA4_TEXT_LAYER_PREFIXES = (
    "model.language_model.layers",
    "model.layers",
)


def _get_train_logger() -> logging.Logger:
    logger = logging.getLogger("LLMs_Train_API")
    logger.setLevel(logging.INFO)
    logger.propagate = False
    if not logger.handlers:
        TRAIN_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        handler = logging.FileHandler(TRAIN_LOG_PATH, encoding="utf-8")
        handler.setFormatter(logging.Formatter("%(asctime)s | %(levelname)s | %(message)s"))
        logger.addHandler(handler)
    return logger


def _train_log(message: str, *args) -> None:
    text = str(message or "")
    try:
        if args:
            text = text % args
    except Exception:
        text = f"{text} {args}"
    try:
        print(text, flush=True)
    except Exception:
        pass
    try:
        _get_train_logger().info(text)
    except Exception:
        pass


def _train_log_exception(message: str, *args) -> None:
    try:
        _get_train_logger().exception(message, *args)
    except Exception:
        pass


def _resolve_data_path() -> str:
    """Prefer train.jsonl generated by /api/train/run; fallback to legacy training.jsonl."""
    data_dir = PROJECT_ROOT / "App" / "LLMs_Train" / "data"
    primary = data_dir / "train.jsonl"
    legacy = data_dir / "training.jsonl"
    return str(primary if primary.exists() else legacy)


DATA_PATH = _resolve_data_path()

MAX_LENGTH = 9000


def _repo_to_hf_cache_dir(repo_id: str) -> str:
    return f"models--{str(repo_id or '').replace('/', '--')}"


def _resolve_hf_snapshot_dir(model_cache_dir: Path) -> str:
    """
    Resolve Hugging Face cached model dir:
    models--xxx/refs/main -> snapshots/<revision>
    """
    refs_main = model_cache_dir / "refs" / "main"
    snapshots_dir = model_cache_dir / "snapshots"

    if refs_main.exists():
        revision = refs_main.read_text(encoding="utf-8").strip()
        snapshot_path = snapshots_dir / revision
        if snapshot_path.exists():
            return str(snapshot_path)

    # fallback: lấy snapshot đầu tiên nếu không có refs/main
    if snapshots_dir.exists():
        snapshot_dirs = [p for p in snapshots_dir.iterdir() if p.is_dir()]
        if len(snapshot_dirs) == 1:
            return str(snapshot_dirs[0])
        if len(snapshot_dirs) > 1:
            snapshot_dirs = sorted(snapshot_dirs, key=lambda p: p.stat().st_mtime, reverse=True)
            return str(snapshot_dirs[0])

    raise FileNotFoundError(f"Could not resolve snapshot dir from: {model_cache_dir}")


def _resolve_base_dir(*, model_id: str, model_cfg: dict | None = None, base_dir: str | None = None) -> str:
    explicit = str(base_dir or "").strip()
    if explicit:
        p = Path(explicit)
        if p.exists():
            return str(p)
        raise FileNotFoundError(f"Base model path not found: {explicit}")

    cfg = model_cfg or {}
    repo_id = str(cfg.get("repo_id") or "").strip()
    if not repo_id:
        repo_id = DEFAULT_QWEN_REPO_ID if str(model_id or "").strip() in {"", DEFAULT_QWEN_MODEL_ID} else ""
    if not repo_id:
        raise ValueError(f"Cannot resolve base model for model_id={model_id!r}: missing repo_id")

    candidates = [
        PROJECT_ROOT / "Models" / "hub" / _repo_to_hf_cache_dir(repo_id),
        PROJECT_ROOT / "Models" / _repo_to_hf_cache_dir(repo_id),
        PROJECT_ROOT / "Models" / str(model_cfg.get("local_id") or model_id or "").strip(),
    ]
    for candidate in candidates:
        if candidate.exists():
            try:
                return _resolve_hf_snapshot_dir(candidate)
            except Exception:
                if (candidate / "config.json").exists():
                    return str(candidate)

    raise FileNotFoundError(f"Could not resolve local base model for model_id={model_id!r}, repo_id={repo_id!r}")


def _sanitize_lora_name(raw_name: str) -> str:
    text = str(raw_name or "").strip()
    if not text:
        return "lora_model"

    text = "".join(
        ch for ch in unicodedata.normalize("NFKD", text)
        if not unicodedata.combining(ch)
    )
    text = text.encode("ascii", "ignore").decode("ascii")
    text = re.sub(r"\s+", "_", text)
    text = re.sub(r"[^A-Za-z0-9._-]", "", text)
    text = re.sub(r"_+", "_", text).strip("._-")
    return text or "lora_model"


def _lora_dir_for_model(model_id: str, lora_name: str, *, model_cfg: dict | None = None) -> str:
    safe_name = _sanitize_lora_name(lora_name)
    normalized_model_id = str(model_id or DEFAULT_QWEN_MODEL_ID).strip()
    repo_id = str((model_cfg or {}).get("repo_id") or "").strip().lower()
    if normalized_model_id == DEFAULT_QWEN_MODEL_ID or repo_id == DEFAULT_QWEN_REPO_ID.lower():
        return str(Path(LORA_ROOT) / safe_name)
    return str(Path(LORA_ROOT) / f"{_sanitize_lora_name(normalized_model_id)}__{safe_name}")


def _existing_lora_dir_for_model(model_id: str, lora_name: str, *, model_cfg: dict | None = None) -> str:
    primary = Path(_lora_dir_for_model(model_id, lora_name, model_cfg=model_cfg))
    if primary.exists():
        return str(primary)

    legacy = Path(LORA_ROOT) / _sanitize_lora_name(lora_name)
    if legacy.exists():
        return str(legacy)
    return str(primary)


def _model_kind(model_id: str, model_cfg: dict | None = None) -> str:
    repo_id = str((model_cfg or {}).get("repo_id") or "").strip().lower()
    mid = str(model_id or "").strip().lower()
    if mid == "gemma_4_e4b_it" or repo_id.startswith("google/gemma-4"):
        return "gemma4"
    return "qwen"


def _get_gemma4_model_loader():
    try:
        import transformers

        loader = getattr(transformers, "AutoModelForMultimodalLM", None)
        if loader is not None:
            return loader
    except Exception:
        pass
    return AutoModelForCausalLM


def _infer_lora_target_modules(model, preferred: list[str]) -> list[str]:
    """Pick LoRA target module suffixes that actually exist in the loaded model."""
    found: set[str] = set()
    try:
        module_names = [name for name, _module in model.named_modules()]
    except Exception:
        module_names = []

    for target in preferred:
        suffix = f".{target}"
        if any(name == target or name.endswith(suffix) for name in module_names):
            found.add(target)

    return [target for target in preferred if target in found]


def _infer_modules_to_save(model, preferred: list[str]) -> list[str]:
    """Pick optional full-rank modules to save only when PEFT can find them."""
    return _infer_lora_target_modules(model, preferred)


def _infer_gemma4_lora_target_modules(model) -> list[str]:
    """Target only Gemma 4 text attention q/k/v/o inner Linear modules."""
    try:
        text_cfg = model.config.get_text_config()
    except Exception:
        text_cfg = getattr(model, "config", None)
    num_layers = int(getattr(text_cfg, "num_hidden_layers", 30) or 30)

    existing: set[str] = set()
    try:
        existing = {str(name or "") for name, _module in model.named_modules()}
    except Exception:
        existing = set()

    targets: list[str] = []
    for prefix in GEMMA4_TEXT_LAYER_PREFIXES:
        for layer_idx in range(num_layers):
            for projection in GEMMA4_ATTENTION_LINEAR_TARGETS:
                name = f"{prefix}.{layer_idx}.{projection}"
                if not existing or name in existing:
                    targets.append(name)

    if targets:
        return targets
    raise ValueError(
        "Could not find Gemma 4 q/k/v/o language-model LoRA targets. "
        "Expected modules like model.language_model.layers.0.self_attn.q_proj.linear"
    )


def _apply_chat_template_for_train(tokenizer, processor, messages, *, add_generation_prompt: bool) -> str:
    target = processor if processor is not None and hasattr(processor, "apply_chat_template") else tokenizer
    return target.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=add_generation_prompt,
    )


def _tokenize_chat_supervised(tokenizer, processor, messages, *, max_length: int) -> dict:
    full_text = _apply_chat_template_for_train(
        tokenizer,
        processor,
        messages,
        add_generation_prompt=False,
    )
    prompt_messages = list(messages or [])
    if prompt_messages and str((prompt_messages[-1] or {}).get("role") or "").lower() == "assistant":
        prompt_messages = prompt_messages[:-1]
    prompt_text = _apply_chat_template_for_train(
        tokenizer,
        processor,
        prompt_messages,
        add_generation_prompt=True,
    )

    result = tokenizer(
        full_text,
        truncation=True,
        max_length=max_length,
        padding=False,
    )
    prompt_ids = tokenizer(
        prompt_text,
        truncation=True,
        max_length=max_length,
        padding=False,
    ).get("input_ids", [])

    labels = list(result["input_ids"])
    mask_len = min(len(prompt_ids), len(labels))
    for idx in range(mask_len):
        labels[idx] = -100
    result["labels"] = labels
    return result


def _supervised_lm_collator(tokenizer):
    pad_token_id = tokenizer.pad_token_id
    if pad_token_id is None:
        pad_token_id = tokenizer.eos_token_id if tokenizer.eos_token_id is not None else 0

    def _collate(features: list[dict]) -> dict:
        max_len = max(len(f.get("input_ids") or []) for f in features)
        input_ids = []
        attention_mask = []
        labels = []
        for feature in features:
            ids = list(feature.get("input_ids") or [])
            mask = list(feature.get("attention_mask") or [1] * len(ids))
            item_labels = list(feature.get("labels") or ids)
            pad_len = max_len - len(ids)
            input_ids.append(ids + [pad_token_id] * pad_len)
            attention_mask.append(mask + [0] * pad_len)
            labels.append(item_labels + [-100] * pad_len)

        return {
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(attention_mask, dtype=torch.long),
            "labels": torch.tensor(labels, dtype=torch.long),
        }

    return _collate


def _train_qwen_lora(*, num_epochs: int, lora_dir: str, old_lora_root: str, has_old_lora: bool, base_dir: str) -> dict:
    tokenizer = None
    model = None
    dataset = None
    trainer = None
    training_args = None
    bnb_config = None

    _train_log("Resolved BASE_DIR: %s", base_dir)

    # Load tokenizer: ưu tiên slow để tránh lỗi fast tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
        base_dir,
        trust_remote_code=True,
        use_fast=False
    )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4"
    )

    model = AutoModelForCausalLM.from_pretrained(
        base_dir,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True
    )

    model.config.use_cache = False
    model.gradient_checkpointing_enable()

    if has_old_lora:
        old_path = Path(old_lora_root)
        if not old_path.exists():
            raise FileNotFoundError(f"Old LoRA not found: {old_lora_root}")
        model = PeftModel.from_pretrained(model, old_lora_root)
        model = model.merge_and_unload()

    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "v_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM"
    )

    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    def format_example(example):
        text = tokenizer.apply_chat_template(
            example["messages"],
            tokenize=False,
            add_generation_prompt=False
        )
        return {"text": text}

    dataset = load_dataset("json", data_files=DATA_PATH)["train"]
    dataset = dataset.map(format_example)

    def tokenize(example):
        result = tokenizer(
            example["text"],
            truncation=True,
            max_length=MAX_LENGTH,
            padding=False
        )
        result["labels"] = result["input_ids"].copy()
        return result

    dataset = dataset.map(tokenize, remove_columns=dataset.column_names)

    training_args = TrainingArguments(
        output_dir=lora_dir,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        num_train_epochs=int(num_epochs),
        learning_rate=5e-5,
        # fp16=True,
        fp16=False,
        bf16=True,
        logging_steps=5,
        save_steps=100,
        save_total_limit=1,
        report_to="none",
        optim="paged_adamw_8bit"
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
    )

    _train_log("Training Qwen LoRA...")
    trainer.train()
    model.save_pretrained(lora_dir)
    tokenizer.save_pretrained(lora_dir)

    return {
        "trainer": trainer,
        "model": model,
        "tokenizer": tokenizer,
        "dataset": dataset,
        "training_args": training_args,
        "bnb_config": bnb_config,
    }


def _train_gemma4_lora(*, num_epochs: int, lora_dir: str, old_lora_root: str, has_old_lora: bool, base_dir: str) -> dict:
    processor = None
    tokenizer = None
    model = None
    dataset = None
    trainer = None
    training_args = None
    bnb_config = None

    _train_log("Resolved BASE_DIR: %s", base_dir)

    proc_kwargs = {"trust_remote_code": True, "backend": "torchvision"}
    try:
        processor = AutoProcessor.from_pretrained(base_dir, **proc_kwargs)
    except TypeError:
        proc_kwargs.pop("backend", None)
        processor = AutoProcessor.from_pretrained(base_dir, **proc_kwargs)
    except AttributeError as e:
        if "backend" in str(e).lower() and "no setter" in str(e).lower():
            proc_kwargs.pop("backend", None)
            processor = AutoProcessor.from_pretrained(base_dir, **proc_kwargs)
        else:
            raise

    tokenizer = getattr(processor, "tokenizer", None)
    if tokenizer is None:
        tokenizer = AutoTokenizer.from_pretrained(base_dir, trust_remote_code=True, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
    )

    model_loader = _get_gemma4_model_loader()
    model = model_loader.from_pretrained(
        base_dir,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
    )

    model.config.use_cache = False
    if hasattr(model, "gradient_checkpointing_enable"):
        model.gradient_checkpointing_enable()

    try:
        from peft import prepare_model_for_kbit_training

        model = prepare_model_for_kbit_training(model)
    except Exception:
        pass

    if has_old_lora:
        old_path = Path(old_lora_root)
        if not old_path.exists():
            raise FileNotFoundError(f"Old LoRA not found: {old_lora_root}")
        model = PeftModel.from_pretrained(model, old_lora_root)
        model = model.merge_and_unload()

    gemma_target_modules = _infer_gemma4_lora_target_modules(model)

    gemma_modules_to_save = _infer_modules_to_save(model, ["lm_head", "embed_tokens"])
    lora_kwargs = {
        "r": 16,
        "lora_alpha": 32,
        "target_modules": gemma_target_modules,
        "lora_dropout": 0.05,
        "bias": "none",
        "task_type": "CAUSAL_LM",
    }
    if gemma_modules_to_save:
        lora_kwargs["modules_to_save"] = gemma_modules_to_save

    _train_log("Gemma LoRA target_modules: %s", gemma_target_modules)
    _train_log("Gemma LoRA modules_to_save: %s", gemma_modules_to_save)

    lora_config = LoraConfig(**lora_kwargs)
    try:
        lora_config.ensure_weight_tying = True
    except Exception:
        pass

    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    dataset = load_dataset("json", data_files=DATA_PATH)["train"]

    def tokenize(example):
        return _tokenize_chat_supervised(
            tokenizer,
            processor,
            example["messages"],
            max_length=MAX_LENGTH,
        )

    dataset = dataset.map(tokenize, remove_columns=dataset.column_names)

    training_args = TrainingArguments(
        output_dir=lora_dir,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        num_train_epochs=int(num_epochs),
        learning_rate=2e-4,
        fp16=False,
        bf16=True,
        logging_steps=5,
        save_steps=100,
        save_total_limit=1,
        report_to="none",
        optim="paged_adamw_8bit",
        remove_unused_columns=False,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        data_collator=_supervised_lm_collator(tokenizer),
    )

    _train_log("Training Gemma 4 LoRA...")
    trainer.train()
    model.save_pretrained(lora_dir)
    tokenizer.save_pretrained(lora_dir)
    if processor is not None:
        try:
            processor.save_pretrained(lora_dir)
        except Exception:
            pass

    return {
        "trainer": trainer,
        "model": model,
        "tokenizer": tokenizer,
        "processor": processor,
        "dataset": dataset,
        "training_args": training_args,
        "bnb_config": bnb_config,
    }


def train_lora(
    num_epochs: int,
    lora_name: str,
    old_lora_name: str = "",
    *,
    model_id: str = DEFAULT_QWEN_MODEL_ID,
    model_cfg: dict | None = None,
    base_dir: str | None = None,
) -> dict:
    import gc

    tokenizer = None
    processor = None
    model = None
    dataset = None
    trainer = None
    training_args = None
    bnb_config = None

    model_id = str(model_id or DEFAULT_QWEN_MODEL_ID).strip() or DEFAULT_QWEN_MODEL_ID
    model_cfg = model_cfg or {}
    safe_name = _sanitize_lora_name(lora_name)
    lora_dir = _lora_dir_for_model(model_id, lora_name, model_cfg=model_cfg)
    Path(lora_dir).mkdir(parents=True, exist_ok=True)

    has_old_lora = bool(str(old_lora_name or "").strip())
    old_lora_root = _existing_lora_dir_for_model(model_id, old_lora_name, model_cfg=model_cfg)
    resolved_base_dir = _resolve_base_dir(model_id=model_id, model_cfg=model_cfg, base_dir=base_dir)
    kind = _model_kind(model_id, model_cfg=model_cfg)

    try:
        if kind == "gemma4":
            _train_log("Training LoRA model_id=%s kind=%s lora_dir=%s", model_id, kind, lora_dir)
            train_state = _train_gemma4_lora(
                num_epochs=num_epochs,
                lora_dir=lora_dir,
                old_lora_root=old_lora_root,
                has_old_lora=has_old_lora,
                base_dir=resolved_base_dir,
            )
        else:
            _train_log("Training LoRA model_id=%s kind=%s lora_dir=%s", model_id, kind, lora_dir)
            train_state = _train_qwen_lora(
                num_epochs=num_epochs,
                lora_dir=lora_dir,
                old_lora_root=old_lora_root,
                has_old_lora=has_old_lora,
                base_dir=resolved_base_dir,
            )

        trainer = train_state.get("trainer")
        model = train_state.get("model")
        tokenizer = train_state.get("tokenizer")
        processor = train_state.get("processor")
        dataset = train_state.get("dataset")
        training_args = train_state.get("training_args")
        bnb_config = train_state.get("bnb_config")
        _train_log("LoRA saved at: %s", lora_dir)
        return {
            "lora_dir": lora_dir,
            "num_epochs": int(num_epochs),
            "safe_name": safe_name,
            "old_lora_name": str(old_lora_name or "").strip(),
            "model_id": model_id,
            "model_kind": kind,
            "base_dir": resolved_base_dir,
        }
    except Exception as e:
        _train_log("Training failed: %s", repr(e))
        _train_log_exception(
            "Training failed traceback: model_id=%s kind=%s lora_dir=%s base_dir=%s",
            model_id,
            kind,
            lora_dir,
            resolved_base_dir,
        )
        raise
    finally:
        try:
            del model
            del trainer
            del tokenizer
            del processor
            del dataset
            del training_args
            del bnb_config
        except Exception:
            pass
        model = None
        trainer = None
        tokenizer = None
        processor = None
        dataset = None
        training_args = None
        bnb_config = None

        try:
            gc.collect()
        except Exception:
            pass

        try:
            if torch.cuda.is_available():
                try:
                    torch.cuda.synchronize()
                except Exception:
                    pass
                for _ in range(3):
                    try:
                        torch.cuda.empty_cache()
                    except Exception:
                        pass
                    try:
                        torch.cuda.ipc_collect()
                    except Exception:
                        pass
                    try:
                        gc.collect()
                    except Exception:
                        pass
        except Exception:
            pass
        _train_log("VRAM cleaned!")
