import fs from "node:fs/promises";
import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";
const path = "E:/Asoft/AI_BEM/AI_BEM_Check_T08_09/DATA_BEM AI_MEIKO_25092026.xlsx";
const workbook = await SpreadsheetFile.importXlsx(await FileBlob.load(path));
const sheet = workbook.worksheets.getItem("Rules_Nguyên vật liệu");
const values = sheet.getRange("O4:O12").values.flat();
console.log("rows", values.length);
console.log("all_have_tinh_huong", values.every(v => String(v).includes("Tình huống")));
console.log("all_have_meiko", values.every(v => String(v).includes("Meiko xác nhận")));
const preview = await workbook.render({ sheetName: "Rules_Nguyên vật liệu", range: "O3:O12", scale: 1, format: "png" });
await fs.writeFile("E:/Asoft/AI_BEM/BEM_AI_PROJECT/.codex-artifact-rules-check/rules_nvl_col_o_preview.png", new Uint8Array(await preview.arrayBuffer()));
