import fs from "node:fs/promises";
import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";
const outDir = "E:/Asoft/AI_BEM/AI_BEM_Check_T08_09/Live_DB_Update_20260928";
const bookPath = "E:/Asoft/AI_BEM/AI_BEM_Check_T08_09/DATA_BEM AI_MEIKO_25092026.xlsx";
const wb = await SpreadsheetFile.importXlsx(await FileBlob.load(bookPath));
const monthPreview = await wb.render({ sheetName: "Kết quả tháng 09 và xử lý", range: "A1:T10", scale: 1, format: "png" });
const dashPreview = await wb.render({ sheetName: "Dashboard T8-09", range: "A1:O23", scale: 1, format: "png" });
await fs.writeFile(`${outDir}/preview_month9_live_20260928.png`, new Uint8Array(await monthPreview.arrayBuffer()));
await fs.writeFile(`${outDir}/preview_dashboard_live_20260928.png`, new Uint8Array(await dashPreview.arrayBuffer()));
console.log('rendered');
