import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";
const inputPath = "E:/Asoft/AI_BEM/AI_BEM_Check_T08_09/DATA_BEM AI_MEIKO_25092026.xlsx";
const outputPath = "E:/Asoft/AI_BEM/AI_BEM_Check_T08_09/DATA_BEM AI_MEIKO_25092026.rules-merged-tmp.xlsx";
const updates = [
  ["- Tình huống: Tên NCC trên PO, Invoice, Ringi hoặc tờ khai viết khác nhau. Ví dụ: “ABC CO., LTD”, “ABC Company Limited”, tên tiếng Nhật hoặc tên viết tắt.\n- Cách xử lý: Bỏ qua khác biệt chữ hoa/thường, dấu câu, khoảng trắng, hậu tố Co., Ltd/Corporation và địa chỉ/chi nhánh nếu cùng mã NCC hoặc cùng đối tượng bán hàng.\n- Kết quả: Xác định là cùng NCC thì OK; khác NCC hoặc không đủ căn cứ thì NG.\n- Cần xác nhận: Khi có mã NCC nội bộ, có ưu tiên kiểm tra theo mã NCC không?"],
  ["- Tình huống: Một tờ khai/bảng kê có nhiều Invoice nhưng ĐNTT chỉ thanh toán một số Invoice.\n- Cách xử lý: Chỉ kiểm tra Invoice ghi trên ĐNTT; Invoice khác trong cùng hồ sơ không tính vào phiếu này. VAT, Commercial Invoice và IV_PL của cùng giao dịch chỉ dùng để kiểm tra chéo, không tính là các Invoice khác nhau.\n- Hàng nội địa: ĐNTT, VAT và PO khớp số Invoice thì OK, không bắt buộc có tờ khai. Hàng nhập khẩu: cần có tờ khai để kiểm tra số Invoice.\n- Kết quả: Số Invoice chỉ khác khoảng trắng, dấu “-”, “/” hoặc ký tự phụ thì xem là khớp sau khi chuẩn hóa.\n- Cần xác nhận: Hàng nội địa có cần thêm chứng từ nào ngoài ĐNTT, VAT và PO không?"],
  ["- Tình huống: Một tờ khai/bảng kê có nhiều Invoice với ngày khác nhau.\n- Cách xử lý: Chỉ lấy ngày của Invoice/VAT/IV_PL đang thanh toán trên ĐNTT; không dùng ngày của Invoice khác.\n- Ví dụ: NVL/09/2026/0001 thanh toán Invoice ngày 06/07/2026; tờ khai cũng thể hiện Invoice này ngày 06/07/2026 thì OK.\n- Hóa đơn điều chỉnh/thay thế: dùng ngày của hóa đơn được thanh toán; hóa đơn điều chỉnh chỉ dùng để giải thích chênh lệch.\n- Cần xác nhận: Nếu hóa đơn gốc và hóa đơn điều chỉnh đều có trên hồ sơ, ưu tiên dùng hóa đơn nào?"],
  ["- Tình huống: Ringi, PO, hợp đồng hoặc tờ khai có nhiều khoản, nhưng ĐNTT chỉ thanh toán một phần.\n- Cách xử lý: Chỉ cộng tiền của đúng NCC, đúng Invoice/VAT, đúng PO/hợp đồng, đúng tờ khai và đúng lần thanh toán.\n- Không cộng trùng tiền khi VAT, Commercial Invoice, IV_PL và tờ khai cùng thể hiện một giao dịch.\n- Ví dụ: Ringi 100.000 USD; lần 1 trả 40.000 USD, lần 2 trả 60.000 USD. Mỗi ĐNTT vẫn OK nếu tổng hai lần không vượt 100.000 USD.\n- Cần xác nhận: Có kiểm soát tổng số tiền đã thanh toán theo Ringi, PO hoặc hợp đồng không?"],
  ["- Tình huống: Invoice có cả nguyên tệ và số tiền quy đổi VND, hoặc một ĐNTT có nhiều Invoice khác loại tiền.\n- Cách xử lý: Kiểm tra theo loại tiền thanh toán trên ĐNTT/Invoice; không dùng tiền thuế hoặc số tiền quy đổi để đối chiếu.\n- Ví dụ: ĐNTT thanh toán USD thì so với số USD trên Invoice. Nếu có nhiều Invoice khác loại tiền thì kiểm tra riêng từng Invoice.\n- Kết quả: Đúng loại tiền của khoản thanh toán thì OK; khác loại tiền thì NG.\n- Cần xác nhận: Có trường hợp nào cho phép thanh toán khác loại tiền ghi trên Invoice không?"],
  ["- Tình huống: Điều kiện giao hàng ghi kèm địa điểm hoặc diễn giải khác nhau. Ví dụ: “FCA NARITA” và “FCA JAPAN”; hoặc tờ khai ghi rõ “DAP = EXW”.\n- Cách xử lý: So theo điều kiện chính FCA/CIF/DDP/DAP/EXW; địa điểm chỉ để tham khảo. DAP và EXW chỉ xem là tương đương khi tờ khai ghi rõ.\n- Nếu một phiếu có nhiều Invoice/PO/tờ khai thì chỉ so trong đúng nhóm chứng từ của Invoice đó, không so chéo.\n- Kết quả: Cùng bản chất thì OK; khác bản chất như FOB và CIF thì NG.\n- Cần xác nhận: Có bắt buộc địa điểm đi kèm điều kiện giao hàng phải giống nhau không?"],
  ["- Tình huống: PO ghi AMS30/60/90, “90 after B/L” hoặc “Within N days after delivery”.\n- Cách xử lý: Với AMS, lấy ngày hàng đến/ngày hoàn thành kiểm tra, cộng số ngày quy định rồi lấy ngày cuối tháng làm hạn thanh toán. Ngày cuối tháng là ngày nghỉ thì lấy ngày làm việc liền trước.\n- Ví dụ: Hàng đến 13/09, AMS30 thì hạn thanh toán là 31/10.\n- Với “90 after B/L” ưu tiên ngày B/L; với “Within N days after delivery” dùng ngày giao hàng có chứng từ. Phiếu đặt cọc không bắt buộc có Invoice/tờ khai.\n- Cần xác nhận: Nếu thiếu B/L hoặc chứng từ giao hàng thì dùng ngày nào để tính hạn?"],
  ["- Tình huống: Hàng nhập khẩu có tờ khai nhưng thiếu ngày hàng đến/ngày hoàn thành kiểm tra.\n- Ảnh hưởng: Không đủ dữ liệu để tính hạn thanh toán.\n- Cách xử lý: Hàng nhập khẩu thiếu ngày này thì cần kiểm tra thủ công. Hàng nội địa không có tờ khai thì bỏ qua tiêu chí này, không báo NG.\n- Cần xác nhận: Khi tờ khai có cả ngày hàng đến và ngày hoàn thành kiểm tra thì dùng ngày nào để tính Deadline? Nếu thiếu cả hai ngày thì kết luận NG hay kiểm tra thủ công?"],
  ["- Tình huống: VAT điện tử có chữ ký số nhưng không có dấu đỏ; PO/Invoice nước ngoài có stamp, logo hoặc xác nhận theo thông lệ.\n- Cách xử lý: Chấp nhận VAT điện tử có chữ ký số hợp lệ. Chứng từ nước ngoài chấp nhận dấu/chữ ký/xác nhận nếu đủ căn cứ nhận diện bên phát hành.\n- Nếu file scan mờ, không nhận diện được chữ ký hoặc con dấu thì chuyển kiểm tra thủ công, không tự kết luận OK.\n- Lưu ý: AI hiện chỉ nhận biết có hoặc không có con dấu; chưa xác định được vị trí và số lượng con dấu cần có.\n- Cần xác nhận: PO, hợp đồng, Invoice trong nước/nước ngoài bắt buộc có chữ ký hoặc con dấu nào?"],
];
const workbook = await SpreadsheetFile.importXlsx(await FileBlob.load(inputPath));
const sheet = workbook.worksheets.getItem("Rules_Nguyên vật liệu");
sheet.getRange("O4:O12").values = updates;
sheet.getRange("O4:O12").format.wrapText = true;
sheet.getRange("O4:O12").format.verticalAlignment = "top";
const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(outputPath);
console.log(outputPath);
